### PR TITLE
add integration test for restart

### PR DESCRIPTION
**Pull request by huan**
Related to #189

### CODE REVIEW

**Comment by huan** [comment]
After added this version of the test, the unit test can pass but will hang forever.

The reason for it I guess might be the `stop()` did not clean all the resources that the puppet has used, for example, timers.

**Comment by huan** [comment]
Can we merge this PR for now?

**Comment by su-chang** [comment]
It can not pass test, maybe something wrong with `stop()`, I will check it later, and then when I resolved this problem, I will merge this PR with green CI.

**Comment by huan** [comment]
Can we merge this PR for now?

**Comment by su-chang** [comment]
Sorry, it can't.

It can not pass the CI test, because of no token for padplus `start()`.

I do not know how to make it skip token verification.

**Comment by huan** [comment]
Understand.

So the question left for us is: How Might We merge this PR?

I hope we can figure it out soon.

**Comment by su-chang** [comment]
Maybe we could not pass the CI test after we revert `flash-store` to `v0.14.1`. Due to some bugs 
about `segmentfault`.

**Comment by su-chang** [comment]
I removed the memory-card for this test, and it could pass start and then stop three times.

But I do not know why it will hang npm test when all test passed.

**Pull request closed without merging**
